# Generated by Django 3.2.10 on 2022-01-01 21:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyWaterIntake',
            new_name='Intake',
        ),
    ]
